{
    'name' : 'Library Management',
    'version' : '1.0',
    'summary': 'Library Management software',
    'sequence': 10,
    'description': """Library Management Software - My First Add-on in odoo""",
    'category': 'Library',
    'website': 'https://www.odoolibrary.tech',
    'version': '14.0.1',
   'depends': ['base'],
    'data': [
        'security/groups.xml',
        'views/library_book.xml',
        'views/library_book_categ.xml',
        'data/data.xml',
        'data/demo.xml',
        'views/library_book_rent.xml',
        'wizard/library_book_rent_wizard.xml',
        'wizard/library_book_return_wizard.xml',
        'views/library_book_statistics.xml',
        'views/res_config_settings_views.xml',
        'views/templates.xml'
    ],
    'post_init_hook': 'add_book_hook',
    'demo': [],
    'qweb': [],
    'installable': True,
    'application': True,
    'auto_install': False,
}